{config, ...}: {
  programs.zsh.initContent = ''
    # Fix ghostty TERM on Linux when terminfo is missing
    if [[ "$TERM" == ghostty* || "$TERM" == xterm-ghostty* ]] && ! infocmp "$TERM" &>/dev/null; then
      export TERM=xterm-256color
    fi

    # Increase file descriptor limit for Rust builds
    ulimit -n 10240

    # Ensure nix-darwin system profile is on PATH
    case ":$PATH:" in
      *":/run/current-system/sw/bin:"*) ;;
      *) export PATH="/run/current-system/sw/bin:$PATH" ;;
    esac

    # If you haven't successfully switched yet, `darwin-rebuild` won't exist.
    # Provide a tiny fallback that uses your flake apps.
    if ! command -v darwin-rebuild >/dev/null 2>&1; then
      darwin-rebuild() {
        case "${"1:-"}" in
          build)
            nix run "$HOME/nix-config#darwin-build"
            ;;
          switch|*)
            nix run "$HOME/nix-config#darwin-switch"
            ;;
        esac
      }
    fi

    # Powerlevel10k user config (generated by p10k configure)
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

    # Prefer Nix-provided runtimes (avoid brew/nvm/conda drift)
    export UV_PYTHON_PREFERENCE="only-system"

    # fzf keybindings/completions (Ctrl-T/Ctrl-R) for zsh.
    if command -v fzf >/dev/null 2>&1; then
      eval "$(fzf --zsh)"
    fi

    # zsh-vi-mode overrides keybindings after init, so we must use its hook.
    # Re-apply fzf bindings for vi keymaps.
    zvm_after_init() {
      bindkey "^R" fzf-history-widget
      bindkey -M viins "^R" fzf-history-widget
      bindkey -M vicmd "^R" fzf-history-widget

      bindkey "^T" fzf-file-widget
      bindkey -M viins "^T" fzf-file-widget
      bindkey -M vicmd "^T" fzf-file-widget
    }

    # Cargo binaries (append so Nix-provided tools win)
    if [ -d "$HOME/.cargo/bin" ]; then
      case ":$PATH:" in
        *":$HOME/.cargo/bin:"*) ;;
        *) export PATH="$PATH:$HOME/.cargo/bin" ;;
      esac
    fi

    # jenv (Java version manager)
    if command -v jenv &>/dev/null; then
      export PATH="$HOME/.jenv/bin:$PATH"
      eval "$(jenv init -)"
    fi

    # fnm (fast node manager) - use different Node versions per project
    if command -v fnm &>/dev/null; then
      eval "$(fnm env --use-on-cd)"
    fi

    # LM Studio CLI
    export PATH="$PATH:${config.home.homeDirectory}/.lmstudio/bin"

    # Solana CLI
    export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

    # Amp CLI
    export PATH="${config.home.homeDirectory}/.amp/bin:$PATH"

    # Local binaries (ocx, etc.)
    export PATH="$HOME/.local/bin:$PATH"

    # Clear screen on shell start
    clear
  '';
}
