{config, ...}: {
  programs.zsh.initContent = ''
    # Increase file descriptor limit for Rust builds
    ulimit -n 10240

    # Ensure nix-darwin system profile is on PATH
    case ":$PATH:" in
      *":/run/current-system/sw/bin:"*) ;;
      *) export PATH="/run/current-system/sw/bin:$PATH" ;;
    esac

    # If you haven't successfully switched yet, `darwin-rebuild` won't exist.
    # Provide a tiny fallback that uses your flake apps.
    if ! command -v darwin-rebuild >/dev/null 2>&1; then
      darwin-rebuild() {
        case "${"1:-"}" in
          build)
            nix run "$HOME/nix-config#darwin-build"
            ;;
          switch|*)
            nix run "$HOME/nix-config#darwin-switch"
            ;;
        esac
      }
    fi

    # Powerlevel10k user config (generated by p10k configure)
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

    # Prefer Nix-provided runtimes (avoid brew/nvm/conda drift)
    export UV_PYTHON_PREFERENCE="only-system"

    # Cargo binaries (append so Nix-provided tools win)
    if [ -d "$HOME/.cargo/bin" ]; then
      case ":$PATH:" in
        *":$HOME/.cargo/bin:"*) ;;
        *) export PATH="$PATH:$HOME/.cargo/bin" ;;
      esac
    fi

    # jenv (Java version manager)
    if command -v jenv &>/dev/null; then
      export PATH="$HOME/.jenv/bin:$PATH"
      eval "$(jenv init -)"
    fi

    # LM Studio CLI
    export PATH="$PATH:${config.home.homeDirectory}/.lmstudio/bin"

    # Solana CLI
    export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

    # Amp CLI
    export PATH="${config.home.homeDirectory}/.amp/bin:$PATH"

    # Clear screen on shell start
    clear
  '';
}
