{
  config,
  pkgs,
  user,
  ...
}: let
  inherit (pkgs.stdenv) isDarwin;
in {
  home = {
    username = user.name;
    homeDirectory = user.home;
    stateVersion = "24.11";

    # Ensure user-installed binaries are on PATH for all shells.
    sessionPath =
      [
        "${config.home.profileDirectory}/bin"
        "${user.home}/.opencode/bin" # OpenCode CLI (installed via curl)
        "${user.home}/.npm-global/bin" # Global npm packages
        "${user.home}/.local/bin" # OCX and other local binaries
      ]
      ++ (
        # macOS/NixOS system profile path
        if isDarwin
        then ["/run/current-system/sw/bin"]
        else []
      );

    sessionVariables =
      {
        EDITOR = "nvim";
        VISUAL = "nvim";
        PAGER = "less";
      }
      // (
        if isDarwin
        then {
          LANG = "en_US.UTF-8";
          LC_ALL = "en_US.UTF-8";
        }
        else {
          # Linux machines often don't have en_US locales generated by default.
          # C.UTF-8 is widely available and avoids locale warnings in tools.
          LANG = "C.UTF-8";
        }
      );
  };

  xdg.enable = true;
}
